name: yy
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.9.24=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.15=h5eee18b_0
  - pip=24.2=py311h06a4308_0
  - python=3.11.10=he870216_0
  - readline=8.2=h5eee18b_0
  - setuptools=75.1.0=py311h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.44.0=py311h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.1.0
      - accelerate==1.0.1
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.10
      - aiosignal==1.3.1
      - alembic==1.13.3
      - annotated-types==0.7.0
      - anyio==4.6.2.post1
      - anytree==2.12.1
      - attrs==24.2.0
      - banal==1.0.6
      - certifi==2024.8.30
      - chardet==5.2.0
      - charset-normalizer==3.4.0
      - click==8.1.7
      - cloudpickle==3.1.0
      - colorama==0.4.6
      - compressed-tensors==0.6.0
      - dataproperty==1.0.1
      - dataset==1.6.2
      - datasets==3.0.1
      - deepspeed==0.14.4
      - dill==0.3.8
      - diskcache==5.6.3
      - distro==1.9.0
      - docker-pycreds==0.4.0
      - einops==0.8.0
      - evaluate==0.4.3
      - fastapi==0.115.2
      - filelock==3.16.1
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - gguf==0.10.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - greenlet==3.1.1
      - h11==0.14.0
      - hjson==3.1.0
      - httpcore==1.0.6
      - httptools==0.6.4
      - httpx==0.27.2
      - huggingface-hub==0.25.2
      - idna==3.10
      - importlib-metadata==8.5.0
      - interegular==0.3.3
      - jinja2==3.1.4
      - jiter==0.6.1
      - joblib==1.4.2
      - jsonlines==4.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - lark==1.2.2
      - llvmlite==0.43.0
      - lm-eval==0.4.5
      - lm-format-enforcer==0.10.6
      - lxml==5.3.0
      - mako==1.3.5
      - markupsafe==3.0.1
      - mbstrdecoder==1.1.3
      - mistral-common==1.4.4
      - more-itertools==10.5.0
      - mpmath==1.3.0
      - msgpack==1.1.0
      - msgspec==0.18.6
      - multidict==6.1.0
      - multiprocess==0.70.16
      - nest-asyncio==1.6.0
      - networkx==3.4.1
      - ninja==1.11.1.1
      - nltk==3.9.1
      - numba==0.60.0
      - numexpr==2.10.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==12.560.30
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.1.105
      - openai==1.52.0
      - opencv-python-headless==4.10.0.84
      - outlines==0.0.46
      - packaging==24.1
      - pandas==2.2.3
      - partial-json-parser==0.2.1.1.post4
      - pathvalidate==3.2.1
      - peft==0.13.2
      - pillow==10.4.0
      - platformdirs==4.3.6
      - portalocker==2.10.1
      - prometheus-client==0.21.0
      - prometheus-fastapi-instrumentator==7.0.0
      - propcache==0.2.0
      - protobuf==5.28.2
      - psutil==6.1.0
      - py-cpuinfo==9.0.0
      - pyairports==2.1.1
      - pyarrow==17.0.0
      - pybind11==2.13.6
      - pycountry==24.6.1
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pynvml==11.5.3
      - pytablewriter==1.2.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - pytz==2024.2
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - ray==2.37.0
      - referencing==0.35.1
      - regex==2024.9.11
      - requests==2.32.3
      - rouge-score==0.1.2
      - rpds-py==0.20.0
      - sacrebleu==2.4.3
      - safetensors==0.4.5
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - sentencepiece==0.2.0
      - sentry-sdk==2.17.0
      - setproctitle==1.3.3
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - sqlalchemy==1.4.54
      - sqlitedict==2.1.0
      - starlette==0.40.0
      - sympy==1.13.1
      - tabledata==1.3.3
      - tabulate==0.9.0
      - tcolorpy==0.1.6
      - threadpoolctl==3.5.0
      - tiktoken==0.7.0
      - tokenizers==0.20.1
      - torch==2.4.0
      - torchvision==0.19.0
      - tqdm==4.66.5
      - tqdm-multiprocess==0.0.11
      - transformers==4.45.2
      - triton==3.0.0
      - typepy==1.3.2
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - urllib3==2.2.3
      - uvicorn==0.32.0
      - uvloop==0.21.0
      - vllm==0.6.3.post1
      - wandb==0.18.5
      - watchfiles==0.24.0
      - websockets==13.1
      - word2number==1.1
      - xformers==0.0.27.post2
      - xxhash==3.5.0
      - yarl==1.15.4
      - zipp==3.20.2
      - zstandard==0.23.0
